//https://projecteuler.net/problem=2
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

package main

import (
	"fmt"
	"strconv"
)

func main() {
	sum := fibEvenSum()
	fmt.Println("Sum is " + strconv.Itoa(sum)) //Sum is 4613732
}

func fibEvenSum() int {
	first := 1
	second := 2
	var third int
	sum := 2
	count := 2
	evenCounter := 2
	for third <= 4000000 {
		third = first + second
		first = second
		second = third
		count++
		if count == evenCounter+3 {
			sum = sum + third
			evenCounter += 3
		}
	}
	return sum
}
